# app/config/security.yml

security:
  encoders:
    LFR\UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    LFR\UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
      provider:  main
    main:
      pattern:   ^/
      anonymous: true
      provider:  main
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
    - { path: /admin/, roles: ROLE_ADMIN, requires_channel: https }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: lefilrougen\.paris$ }
