# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          robin:  { password: robin, roles: [ 'ROLE_USER' ] }
          johann:  { password: johann, roles: [ 'ROLE_USER' ] }
          alienor:  { password: alienor, roles: [ 'ROLE_USER' ] }
          mathilde:  { password: mathilde, roles: [ 'ROLE_USER' ] }
          theo:  { password: theo, roles: [ 'ROLE_USER' ] }
          armande:  { password: armande, roles: [ 'ROLE_USER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
