lfr_store_start:
    path:     /
    defaults: { _controller: LFRStoreBundle:Home:animation }
lfr_store_homepage:
    path:     /accueil
    defaults: { _controller: LFRStoreBundle:Home:homepage }
lfr_store_explore:
    path:     /explore/{type}
    defaults: { _controller: LFRStoreBundle:Search:start, type:"vetement" }
lfr_store_show:
    path:     /show/{id}
    defaults: { _controller: LFRStoreBundle:Search:show, id:0 }
lfr_store_history:
    path:     /histoire
    defaults: { _controller: LFRStoreBundle:Information:history }

lfr_admin_text_add:
    path:     /admin/text/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:textAdd, id:0 }
lfr_admin_image_add:
    path:     /admin/image/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:imageAdd, id:0 }
