lfr_store_work:
    path:     /work
    defaults: { _controller: LFRStoreBundle:Home:work }

lfr_store_start:
    path:     /
    defaults: { _controller: LFRStoreBundle:Home:animation }
lfr_store_homepage:
    path:     /accueil
    defaults: { _controller: LFRStoreBundle:Home:homepage }
lfr_store_collection:
    path:     /collections
    defaults: { _controller: LFRStoreBundle:Information:collection }
lfr_store_explore:
    path:     /collection/{collection}/{category}
    defaults: { _controller: LFRStoreBundle:Search:collection, collection:"_", category:"_" }
lfr_store_show:
    path:     /show/{id}
    defaults: { _controller: LFRStoreBundle:Search:show, id:0 }
lfr_store_creation_love:
    path:     /creation/love/{id}
    defaults: { _controller: LFRStoreBundle:Creation:love, id:0 }
lfr_store_creation_unlove:
    path:     /creation/unlove/{id}
    defaults: { _controller: LFRStoreBundle:Creation:unlove, id:0 }
lfr_store_history:
    path:     /histoire
    defaults: { _controller: LFRStoreBundle:Information:history }
lfr_store_contact:
    path:     /contact
    defaults: { _controller: LFRStoreBundle:Information:contact }
lfr_store_selection:
    path:     /selection
    defaults: { _controller: LFRStoreBundle:Search:selection }

lfr_admin_register:
    path:     /register
    defaults: { _controller: LFRStoreBundle:Admin:register }

lfr_admin_init_create:
    path:     /admin_init/{key}
    defaults: { _controller: LFRStoreBundle:Admin:createAdmin }
lfr_admin_user_add:
    path:     /admin/user/add/{id}
    defaults: { _controller: LFRStoreBundle:Admin:addUser, id: 0 }
lfr_admin_users_show:
    path:     /admin/users/show
    defaults: { _controller: LFRStoreBundle:Admin:showUsers }
lfr_admin_user_remove:
    path:     /admin/user/remove/{id}
    defaults: { _controller: LFRStoreBundle:Admin:removeUser }
lfr_admin_text_add:
    path:     /admin/text/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:textAdd, id:0 }
lfr_admin_image_add:
    path:     /admin/image/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:imageAdd, id:0 }
lfr_admin_gender_add:
    path:     /admin/gender/add/{id}
    defaults: { _controller: LFRStoreBundle:Search:genderAdd, id:0 }
lfr_admin_gender_remove:
    path:     /admin/gender/remove/{id}
    defaults: { _controller: LFRStoreBundle:Search:genderRemove}
lfr_admin_type_add:
    path:     /admin/type/add/{gender_id}/{id}
    defaults: { _controller: LFRStoreBundle:Search:typeAdd, id:0 }
lfr_admin_type_remove:
    path:     /admin/type/remove/{id}
    defaults: { _controller: LFRStoreBundle:Search:typeRemove}
lfr_admin_creation:
    path:     /admin/creation/
    defaults: { _controller: LFRStoreBundle:Creation:index}
lfr_admin_creation_add:
    path:     /admin/creation/add/{id}
    defaults: { _controller: LFRStoreBundle:Creation:add, id:0 }
lfr_admin_creation_show:
    path:     /creation/{id}
    defaults: { _controller: LFRStoreBundle:Creation:show }
    requirements:
        id:   \d+
lfr_admin_creation_remove:
    path:     /admin/creation/remove/{id}
    defaults: { _controller: LFRStoreBundle:Creation:remove}
lfr_admin_collection_add:
    path:     /admin/collection/add/{id}
    defaults: { _controller: LFRStoreBundle:Collection:add, id:0 }
lfr_admin_collection_show:
    path:     /admin/collection/{id}
    defaults: { _controller: LFRStoreBundle:Collection:show }
    requirements:
        id:   \d+
lfr_admin_collection_remove:
    path:     /admin/collection/remove/{id}
    defaults: { _controller: LFRStoreBundle:Collection:remove}
lfr_admin_category_add:
    path:     /admin/category/add/{id}
    defaults: { _controller: LFRStoreBundle:Category:add, id:0 }
lfr_admin_category_show:
    path:     /admin/category/{id}
    defaults: { _controller: LFRStoreBundle:Category:show }
    requirements:
        id:   \d+
lfr_admin_category_remove:
    path:     /admin/category/remove/{id}
    defaults: { _controller: LFRStoreBundle:Category:remove}
lfr_admin_creation_attributes:
    path:     /admin/attributes/
    defaults: { _controller: LFRStoreBundle:Attribute:index}
lfr_admin_creation_attribute_add:
    path:     /admin/attributes/add/{id}/{category}
    defaults: { _controller: LFRStoreBundle:Attribute:add, id:0, category:0}
    requirements:
        id:   \d+
lfr_admin_creation_attribute_remove:
    path:     /admin/attributes/remove/{id}
    defaults: { _controller: LFRStoreBundle:Attribute:remove}
