lfr_store_start:
    path:     /
    defaults: { _controller: LFRStoreBundle:Home:animation }
lfr_store_homepage:
    path:     /accueil
    defaults: { _controller: LFRStoreBundle:Home:homepage }
lfr_store_explore:
    path:     /explore/{type}
    defaults: { _controller: LFRStoreBundle:Search:start, type:"vetement" }
lfr_store_show:
    path:     /show/{id}
    defaults: { _controller: LFRStoreBundle:Search:show, id:0 }
lfr_store_history:
    path:     /histoire
    defaults: { _controller: LFRStoreBundle:Information:history }
lfr_store_contact:
    path:     /contact
    defaults: { _controller: LFRStoreBundle:Information:contact }

lfr_admin_text_add:
    path:     /admin/text/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:textAdd, id:0 }
lfr_admin_image_add:
    path:     /admin/image/add/{id}
    defaults: { _controller: LFRStoreBundle:Information:imageAdd, id:0 }
lfr_admin_gender_add:
    path:     /admin/gender/add/{id}
    defaults: { _controller: LFRStoreBundle:Search:genderAdd, id:0 }
lfr_admin_gender_remove:
    path:     /admin/gender/remove/{id}
    defaults: { _controller: LFRStoreBundle:Search:genderRemove}
lfr_admin_type_add:
    path:     /admin/type/add/{gender_id}/{id}
    defaults: { _controller: LFRStoreBundle:Search:typeAdd, id:0 }
lfr_admin_type_remove:
    path:     /admin/type/remove/{id}
    defaults: { _controller: LFRStoreBundle:Search:typeRemove}
lfr_admin_creation:
    path:     /admin/creation/
    defaults: { _controller: LFRStoreBundle:Creation:index}
lfr_admin_creation_add:
    path:     /admin/creation/add/{id}
    defaults: { _controller: LFRStoreBundle:Creation:add, id:0 }
lfr_admin_creation_show:
    path:     /admin/creation/{id}
    defaults: { _controller: LFRStoreBundle:Creation:show }
    requirements:
        id:   \d+
lfr_admin_creation_remove:
    path:     /admin/creation/remove/{id}
    defaults: { _controller: LFRStoreBundle:Creation:remove}
