services:
#    lfr_store.example:
#        class: LFR\StoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    lfr_store.imagehandler:
        class: LFR\StoreBundle\Imagehandler\LFRImagehandler
        arguments: [%img_dir%]
