rpz_discussion_article:
    path:     /
    defaults: { _controller: RPZDiscussionBundle:Article:index }
rpz_discussion_article_show:
    path:     /show/{id}
    defaults: { _controller: RPZDiscussionBundle:Article:show }
rpz_discussion_article_add:
    path:     /write/{id}
    defaults: { _controller: RPZDiscussionBundle:Article:add, id: 0 }
rpz_discussion_article_edit:
    path:     /edit/{id}
    defaults: { _controller: RPZDiscussionBundle:Article:edit, id: 0 }
rpz_discussion_article_remove:
    path:     /remove/{id}
    defaults: { _controller: RPZDiscussionBundle:Article:remove, id: 0 }
rpz_discussion_comment_add:
    path:     /article/{article_id}/comment/{id}
    defaults: { _controller: RPZDiscussionBundle:Comment:add, id: 0 }
rpz_discussion_comment_edit:
    path:     /article/{article_id}/edit/{id}
    defaults: { _controller: RPZDiscussionBundle:Comment:edit, id: 0 }
rpz_discussion_comment_remove:
    path:     /comment/remove/{id}
    defaults: { _controller: RPZDiscussionBundle:Comment:remove, id: 0 }
rpz_profile:
    path:     /user/all
    defaults: { _controller: RPZDiscussionBundle:User:index}
rpz_profile_edit:
    path:     /profile
    defaults: { _controller: RPZDiscussionBundle:User:edit}
rpz_log:
    path:     /logs
    defaults: { _controller: RPZDiscussionBundle:Log:index}
rpz_log_show:
    path:     /logs/activity
    defaults: { _controller: RPZDiscussionBundle:Log:show}
